#!/usr/bin/env bash
# cluster/setup.sh — set up the whole cluster from scratch. Run it ON THE HEAD box.
#
# If there's no cluster.yaml it ASKS you for each box (ssh IP + user, password once) and BUILDS cluster.yaml
# for you — installing an ssh key, auto-detecting the network + GPU (so you don't need to know iface/HCA names),
# and picking the interconnect. Then for every box it verifies docker/GPU, makes the models dir, and opens the
# firewall (ufw allow from each peer's interconnect IP). Idempotent + rerunnable. `cluster/add.sh <box>` adds one.
set -euo pipefail
cd "$(dirname "$0")/.."                      # repo root
# shellcheck source=cluster/lib.sh
source cluster/lib.sh

# 0a. how many boxes? A SOLO box has no cluster to set up — no wizard, no interconnect, no firewall
#     mesh, no topology. Just provision THIS machine (docker/GPU check, models dir, dashboard key) and
#     write a minimal cluster.yaml naming it, so dashboards and future `cluster/add.sh` have an anchor.
read -rp "How many boxes? [1]: " _n; _n="${_n:-1}"
if [ "$_n" = "1" ]; then
  if [ ! -f cluster.yaml ]; then
    printf '# generated by cluster/setup.sh — SOLO box (gitignored). Recipes need no cluster: block;\n# this entry names THIS machine for dashboards/tooling. cluster/add.sh grows it into a cluster.\nboxes:\n  box1:\n    host: 127.0.0.1\n    ssh_user: %s\n' "$USER" > cluster.yaml
    echo "→ wrote cluster.yaml (solo: this box as box1 @ 127.0.0.1)"
  fi
  echo "── solo box (box1 = this machine) ──"
  install_key box1                 # key auth to localhost (password once if not already set up)
  install_dashboard_key box1       # sparkdash's dedicated key
  provision_box box1
  echo "✓ solo box ready — run recipes WITHOUT a cluster: block. To grow into a cluster later:"
  echo "  cluster/add.sh <box>  (or delete cluster.yaml and rerun cluster/setup.sh)"
  exit 0
fi

# 0b. multi-box: this whole thing runs over ssh — if any box's ufw blocks port 22 we can't get in to fix it.
echo "This sets up your cluster over ssh (port 22). Make sure EVERY box allows ssh first —"
echo "if ufw is blocking it, on that box run:  sudo ufw allow OpenSSH   (otherwise setup can't connect)."
read -rp "All boxes have ssh (port 22) open? [y/N]: " _ok
case "$_ok" in [Yy]*) ;; *) echo "Open ssh on the boxes, then rerun cluster/setup.sh."; exit 1;; esac

# 1. cluster.yaml — build it interactively if missing (you provide ip/user/password; the script fills it in).
if [ ! -f cluster.yaml ]; then
  echo "No cluster.yaml yet — let's set up your cluster (Ctrl-C to abort)."
  echo "For each box give its ssh IP + user (+ password once); I install a key, detect its network + GPU,"
  echo "and write cluster.yaml. The FIRST box is the head (this machine)."
  printf '# generated by cluster/setup.sh — this cluster (gitignored)\nboxes:\n' > cluster.yaml
  i=1; added=0
  while wizard_add_box "box$i"; do
    added=$((added+1)); i=$((i+1))
    read -rp "Add another box? [y/N]: " m; case "$m" in [Yy]*) ;; *) break;; esac
  done
  [ "$added" -ge 1 ] || { echo "no boxes added — aborting"; rm -f cluster.yaml; exit 1; }
  echo "→ wrote cluster.yaml ($added box(es))"
fi

BOXES="$(cy_boxes)"
[ -n "$BOXES" ] || { echo "cluster.yaml has no boxes"; exit 1; }
echo "── boxes: $BOXES ──"

# 1b. hard verify ssh reachability before touching anything (clear error + unblock instructions if not).
echo "── checking ssh reachability (port 22) ──"
preflight_reachable || { echo "✗ open ssh on the box(es) above, then rerun."; exit 1; }

# 2. ensure each box is reachable + has docker/GPU/models dir (install_key is a no-op once ssh works, so this
#    is safe both right after the wizard and on a rerun against an existing cluster.yaml).
for box in $BOXES; do
  echo "── $box  (ssh $(box_target "$box"), interconnect $(box_ic "$box")) ──"
  install_key "$box"
  install_dashboard_key "$box"     # dedicated disposable key the dashboard uses (never the admin key)
  provision_box "$box"
done

# 3. firewall — open EVERY interconnect IP of every box on all boxes (needs sudo; one prompt per box).
echo "── firewall (ufw allow all interconnect IPs; sudo may prompt) ──"
mesh_firewall

# 4. topology discovery (LAST — needs firewalls open). Maps which links reach which boxes + sets NCCL ifaces.
echo "── discovering topology (cluster/mesh.sh) ──"
cluster/mesh.sh || echo "  ⚠ mesh discovery had issues — fix connectivity and rerun cluster/mesh.sh"

echo "✓ cluster ready — reference it in a recipe:  cluster: {boxes: [$(echo "$BOXES" | tr ' ' ', ' | sed 's/, $//')]}"
